AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - snapbot.gemspec

Style/StderrPuts:
  Exclude:
    - lib/snapbot/diagram/renderer.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
