AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - Steepfile

Metrics/AbcSize:
  Exclude:
    - spec/support/fixture_database.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - snapbot.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/support/fixture_database.rb

Style/StderrPuts:
  Exclude:
    - lib/snapbot/diagram/renderer.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
