module Snapbot
  module Diagram
    # Render some DOT via Graphviz dot command line
    class Renderer
      INSTALL_GRAPHVIZ_URL: "https://graphviz.org/download/#executable-packages"
      OUTPUT_FILENAME: "tmp/models.svg"

      @dot: String

      def initialize: (String dot) -> void
      def save: () -> String

      private

      def graphviz_executable: () -> ::String
      def ensure_graphviz: () -> void
    end
  end
end
