name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.4'
          - '3.3.8'
          - '3.2.8'

    steps:
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Check rubocop version
      run: bundle exec rubocop -v
    - name: Run the default task
      run: bundle exec rake
